server: 
    port: 8089
spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/ejercicio_practico_db
    username: postgres
    password: psql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka